name: Deploy to KIND cluster

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: |
         maheshtodkar/myresume-website:latest
         maheshtodkar/myresume-website:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v4
    
    - name: Deploy to KIND on EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        timeout: 120s
        script: |

          bash ./script/setup.sh
          
          kind delete cluster --name portfolio || true
          kind create cluster --config kind-config.yaml --name portfolio

          '''

          cd /home/ubuntu/myproject/Portfolio-website
          git pull origin main || git clone -b main https://github.com/MaheshTodkar1/Portfolio-website.git .
          
          # Set kubectl context
          kubectl config use-context kind-portfolio
          
          # Apply manifests (remove secrets.yaml since not needed)
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml

          # Restart deployment to ensure new image is pulled
          kubectl rollout restart deployment/website-deployment
          
          # Wait for rollout
          kubectl rollout status deployment/website-deployment --timeout=120s
